### ISSUE TITLE
log4net error when running on Linux

### ISSUE THREAD

**Issue by Greelan** [RainOrigami/BattleBitAPIRunner#15]
I'm getting the following error with the latest release when running on Linux:

```
log4net:ERROR Could not create Appender [ColoredConsoleAppender] of type [log4net.Appender.ColoredConsoleAppender]. Reported error follows.
System.DllNotFoundException: Unable to load shared library 'Kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libKernel32.dll: cannot open shared object file: No such file or directory
   at log4net.Appender.ColoredConsoleAppender.GetConsoleOutputCP()
   at log4net.Appender.ColoredConsoleAppender.ActivateOptions()
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)
log4net:ERROR Appender named [ColoredConsoleAppender] not found.
```

Would using `ManagedColoredConsoleAppender` be better to use as per the last comment here? https://stackoverflow.com/questions/64109799/log4neterror-could-not-create-appender-console-of-type-log4net-appender-colo

**Comment by RainOrigami** [comment]
use this, will fix next version

```xml
<?xml version="1.0" encoding="utf-8" ?>
<log4net>
    <root>
        <level value="INFO" />
        <appender-ref ref="ManagedColoredConsoleAppender" />
    </root>
    <appender name="ManagedColoredConsoleAppender" type="log4net.Appender.ManagedColoredConsoleAppender">
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%date [%logger] %level - %message%newline" />
        </layout>
		<mapping>
			<level value="WARN" />
			<foreColor value="Yellow" />
		</mapping>
		<mapping>
			<level value="ERROR" />
			<foreColor value="Red" />
		</mapping>
    </appender>
</log4net>
```

in your log4net.config

**Comment by Greelan** [comment]
Might want to remove the wontfix label lol
